/* Generated by SharpKit 5 v5.5.0 */
if (typeof ($Inherit) == 'undefined') {
	var $Inherit = function (ce, ce2) {

		if (typeof (Object.getOwnPropertyNames) == 'undefined') {

			for (var p in ce2.prototype)
				if (typeof (ce.prototype[p]) == 'undefined' || ce.prototype[p] == Object.prototype[p])
					ce.prototype[p] = ce2.prototype[p];
			for (var p in ce2)
				if (typeof (ce[p]) == 'undefined')
					ce[p] = ce2[p];
			ce.$baseCtor = ce2;

		} else {

			var props = Object.getOwnPropertyNames(ce2.prototype);
			for (var i = 0; i < props.length; i++)
				if (typeof (Object.getOwnPropertyDescriptor(ce.prototype, props[i])) == 'undefined')
					Object.defineProperty(ce.prototype, props[i], Object.getOwnPropertyDescriptor(ce2.prototype, props[i]));

			for (var p in ce2)
				if (typeof (ce[p]) == 'undefined')
					ce[p] = ce2[p];
			ce.$baseCtor = ce2;

		}

	}
};


if (typeof(FoodApp) == "undefined")
    var FoodApp = {};
if (typeof(FoodApp.Common) == "undefined")
    FoodApp.Common = {};
if (typeof(FoodApp.Common.Model) == "undefined")
    FoodApp.Common.Model = {};
FoodApp.Common.Model.ngModelBase = function (){
};
FoodApp.Common.Model.ngFoodItem = function (){
    this.Name = null;
    this.Description = null;
    this.Category = null;
    this.Price = 0;
    this.FoodId = null;
    this.IsByWeightItem = false;
    this.isContainer = false;
    this.isSmallContainer = false;
    this.isBigContainer = false;
    this.isSalat = false;
    this.isGarnir = false;
    this.isMeatOrFish = false;
    this.isFirst = false;
    this.isKvasolevaOrChanachi = false;
};
$Inherit(FoodApp.Common.Model.ngFoodItem, FoodApp.Common.Model.ngModelBase);
FoodApp.Common.Model.ngFoodRate = function (){
    this.FoodId = null;
    this.Rate = 0;
};
$Inherit(FoodApp.Common.Model.ngFoodRate, FoodApp.Common.Model.ngModelBase);
FoodApp.Common.Model.ngHistoryEntry = function (){
    this.FoodId = null;
    this.Date = System.DateTime.MinValue;
    this.Count = 0;
    this.FoodPrice = 0;
};
$Inherit(FoodApp.Common.Model.ngHistoryEntry, FoodApp.Common.Model.ngModelBase);
FoodApp.Common.Model.ngHistoryGroupEntry = function (){
    this.DateStr = null;
    this.Entries = null;
    this.Entries = new System.Collections.Generic.List$1.ctor("FoodApp.Common.Model.ngHistoryEntry");
};
$Inherit(FoodApp.Common.Model.ngHistoryGroupEntry, FoodApp.Common.Model.ngModelBase);
FoodApp.Common.Model.ngOrderEntry = function (){
    this.FoodId = null;
    this.Count = 0;
    this.FoodPrice = 0;
};
$Inherit(FoodApp.Common.Model.ngOrderEntry, FoodApp.Common.Model.ngModelBase);
FoodApp.Common.Model.ngUserModel = function (){
    this.Column = 0;
    this.Email = null;
    this.Name = null;
    this.Id = null;
    this.Picture = null;
    this.GoogleName = null;
    this.IsAdmin = false;
    this.GoogleFirstName = null;
};
$Inherit(FoodApp.Common.Model.ngUserModel, FoodApp.Common.Model.ngModelBase);

