/* Generated by SharpKit 5 v5.5.0 */

if (typeof(angularjs) == "undefined")
    var angularjs = {};
angularjs.clientAppHelper = function (){
    this._controllers =  [];
    this.isDebug = true;
    this.module = null;
};
angularjs.clientAppHelper.inst = new angularjs.clientAppHelper();
angularjs.clientAppHelper.c_sModuleName = "StudyLogApiApp";
angularjs.clientAppHelper.prototype.registerController = function (angularController){
    this._controllers.push(angularController);
};
angularjs.clientAppHelper.prototype.linkWithAngularJs = function (angularController){
    var func1 = new Function("$scope", "$http", "$location", "$filter", angularController.get_namespace() + "." + angularController.get_name() + ".inst.init($scope,$http,$location,$filter)");
    var str = "StudyLogApiApp.controller(\'" + angularController.get_name() + "\',func1);";
    eval(str);
};
angularjs.clientAppHelper.prototype.before = function (){
    this.module = angular.module("StudyLogApiApp",  []);
    window["StudyLogApiApp"] = this.module;
};
angularjs.clientAppHelper.prototype.after = function (){
    for (var i = 0; i < this._controllers.length; ++i){
        this.linkWithAngularJs(this._controllers[i]);
    }
    angularjs.clientAppHelper.addFilter();
};
angularjs.clientAppHelper.addFilter = function (){
    eval("StudyLogApiApp.filter(\'rawHtml\', [\'$sce\', function($sce){return function(val) {return $sce.trustAsHtml(val);};}]);");
};
angularjs.ProgramBefore = function (){
};
angularjs.clientAppHelper.inst.before();
angularjs.angularController = function (){
    this._scope = null;
    this._http = null;
    this._location = null;
    this.Filter = null;
    angularjs.clientAppHelper.inst.registerController(this);
};
angularjs.angularController.prototype.get__model = function (){
    var scope = this._scope instanceof Object ? this._scope : null;
    var obj = scope["model"];
    return obj;
};
angularjs.angularController.prototype.set__model = function (value){
    var scope = this._scope instanceof Object ? this._scope : null;
    scope["model"] = value;
};
angularjs.angularController.prototype.init = function (scope, http, loc, filter){
    this._scope = scope;
    this._http = http;
    this._location = loc;
    this.Filter = filter;
    var copy = this;
    for (var key in copy){
        scope[key] = copy[key];
    }
};

